// Code generated by pkg/config/schema/codegen/tools/collections.main.go. DO NOT EDIT.

package kind

const (
	Unknown Kind = iota
	Address
	BackendTLSPolicy
	ConfigMap
	DNSName
	DaemonSet
	Deployment
	EndpointSlice
	Endpoints
	EnvoyFilter
	GRPCRoute
	GatewayClass
	HTTPRoute
	InferencePool
	KubernetesGateway
	Namespace
	Node
	Pod
	ReferenceGrant
	Secret
	Service
	ServiceAccount
	StatefulSet
	TCPRoute
	TLSRoute
	UDPRoute
	WasmPlugin
	XBackendTrafficPolicy
)

func (k Kind) String() string {
	switch k {
	case Address:
		return "Address"
	case BackendTLSPolicy:
		return "BackendTLSPolicy"
	case ConfigMap:
		return "ConfigMap"
	case DNSName:
		return "DNSName"
	case DaemonSet:
		return "DaemonSet"
	case Deployment:
		return "Deployment"
	case EndpointSlice:
		return "EndpointSlice"
	case Endpoints:
		return "Endpoints"
	case EnvoyFilter:
		return "EnvoyFilter"
	case GRPCRoute:
		return "GRPCRoute"
	case GatewayClass:
		return "GatewayClass"
	case HTTPRoute:
		return "HTTPRoute"
	case InferencePool:
		return "InferencePool"
	case KubernetesGateway:
		return "KubernetesGateway"
	case Namespace:
		return "Namespace"
	case Node:
		return "Node"
	case Pod:
		return "Pod"
	case ReferenceGrant:
		return "ReferenceGrant"
	case Secret:
		return "Secret"
	case Service:
		return "Service"
	case ServiceAccount:
		return "ServiceAccount"
	case StatefulSet:
		return "StatefulSet"
	case TCPRoute:
		return "TCPRoute"
	case TLSRoute:
		return "TLSRoute"
	case UDPRoute:
		return "UDPRoute"
	case WasmPlugin:
		return "WasmPlugin"
	case XBackendTrafficPolicy:
		return "XBackendTrafficPolicy"
	default:
		return "Unknown"
	}
}

func FromString(s string) Kind {
	switch s {
	case "Address":
		return Address
	case "BackendTLSPolicy":
		return BackendTLSPolicy
	case "ConfigMap":
		return ConfigMap
	case "DNSName":
		return DNSName
	case "DaemonSet":
		return DaemonSet
	case "Deployment":
		return Deployment
	case "EndpointSlice":
		return EndpointSlice
	case "Endpoints":
		return Endpoints
	case "EnvoyFilter":
		return EnvoyFilter
	case "GRPCRoute":
		return GRPCRoute
	case "GatewayClass":
		return GatewayClass
	case "HTTPRoute":
		return HTTPRoute
	case "InferencePool":
		return InferencePool
	case "KubernetesGateway":
		return KubernetesGateway
	case "Namespace":
		return Namespace
	case "Node":
		return Node
	case "Pod":
		return Pod
	case "ReferenceGrant":
		return ReferenceGrant
	case "Secret":
		return Secret
	case "Service":
		return Service
	case "ServiceAccount":
		return ServiceAccount
	case "StatefulSet":
		return StatefulSet
	case "TCPRoute":
		return TCPRoute
	case "TLSRoute":
		return TLSRoute
	case "UDPRoute":
		return UDPRoute
	case "WasmPlugin":
		return WasmPlugin
	case "XBackendTrafficPolicy":
		return XBackendTrafficPolicy
	default:
		return Unknown
	}
}
