// Code generated by pkg/config/schema/codegen/tools/collections.main.go. DO NOT EDIT.

package gvr

import "k8s.io/apimachinery/pkg/runtime/schema"

var (
	BackendTLSPolicy           = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1", Resource: "backendtlspolicies"}
	ConfigMap                  = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "configmaps"}
	DaemonSet                  = schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "daemonsets"}
	Deployment                 = schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "deployments"}
	EndpointSlice              = schema.GroupVersionResource{Group: "discovery.k8s.io", Version: "v1", Resource: "endpointslices"}
	Endpoints                  = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "endpoints"}
	EnvoyFilter                = schema.GroupVersionResource{Group: "networking.istio.io", Version: "v1alpha3", Resource: "envoyfilters"}
	GRPCRoute                  = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1", Resource: "grpcroutes"}
	GRPCRoute_v1alpha2         = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "grpcroutes"}
	GatewayClass               = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1", Resource: "gatewayclasses"}
	GatewayClass_v1alpha2      = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "gatewayclasses"}
	GatewayClass_v1beta1       = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1beta1", Resource: "gatewayclasses"}
	HTTPRoute                  = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1", Resource: "httproutes"}
	HTTPRoute_v1alpha2         = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "httproutes"}
	HTTPRoute_v1beta1          = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1beta1", Resource: "httproutes"}
	InferencePool              = schema.GroupVersionResource{Group: "inference.networking.k8s.io", Version: "v1", Resource: "inferencepools"}
	KubernetesGateway          = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1", Resource: "gateways"}
	KubernetesGateway_v1alpha2 = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "gateways"}
	KubernetesGateway_v1beta1  = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1beta1", Resource: "gateways"}
	Namespace                  = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "namespaces"}
	Node                       = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "nodes"}
	Pod                        = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "pods"}
	ReferenceGrant             = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1beta1", Resource: "referencegrants"}
	ReferenceGrant_v1alpha2    = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "referencegrants"}
	Secret                     = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "secrets"}
	Service                    = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "services"}
	ServiceAccount             = schema.GroupVersionResource{Group: "", Version: "v1", Resource: "serviceaccounts"}
	StatefulSet                = schema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "statefulsets"}
	TCPRoute                   = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "tcproutes"}
	TLSRoute                   = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "tlsroutes"}
	UDPRoute                   = schema.GroupVersionResource{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Resource: "udproutes"}
	WasmPlugin                 = schema.GroupVersionResource{Group: "extensions.istio.io", Version: "v1alpha1", Resource: "wasmplugins"}
	XBackendTrafficPolicy      = schema.GroupVersionResource{Group: "gateway.networking.x-k8s.io", Version: "v1alpha1", Resource: "xbackendtrafficpolicies"}
)

func IsClusterScoped(g schema.GroupVersionResource) bool {
	switch g {
	case BackendTLSPolicy:
		return false
	case ConfigMap:
		return false
	case DaemonSet:
		return false
	case Deployment:
		return false
	case EndpointSlice:
		return false
	case Endpoints:
		return false
	case EnvoyFilter:
		return false
	case GRPCRoute:
		return false
	case GRPCRoute_v1alpha2:
		return false
	case GatewayClass:
		return true
	case GatewayClass_v1alpha2:
		return true
	case GatewayClass_v1beta1:
		return true
	case HTTPRoute:
		return false
	case HTTPRoute_v1alpha2:
		return false
	case HTTPRoute_v1beta1:
		return false
	case InferencePool:
		return false
	case KubernetesGateway:
		return false
	case KubernetesGateway_v1alpha2:
		return false
	case KubernetesGateway_v1beta1:
		return false
	case Namespace:
		return true
	case Node:
		return true
	case Pod:
		return false
	case ReferenceGrant:
		return false
	case ReferenceGrant_v1alpha2:
		return false
	case Secret:
		return false
	case Service:
		return false
	case ServiceAccount:
		return false
	case StatefulSet:
		return false
	case TCPRoute:
		return false
	case TLSRoute:
		return false
	case UDPRoute:
		return false
	case WasmPlugin:
		return false
	case XBackendTrafficPolicy:
		return false
	}
	// shouldn't happen
	return false
}
