


apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: 'envoy-gateway-system'
  labels:
    helm.sh/chart: gateway-helm-v1.7.2
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/instance: envoy-gateway
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
data:
  envoy-gateway.yaml: |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    extensionApis:
      enableBackend: true
      enableEnvoyPatchPolicy: true
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    logging:
      level:
        default: info
    provider:
      kubernetes:
        rateLimitDeployment:
          container:
            image: envoyproxy/ratelimit:0141a24f
          patch:
            type: StrategicMerge
            value:
              spec:
                template:
                  spec:
                    containers:
                      - imagePullPolicy: IfNotPresent
                        name: envoy-ratelimit
          pod:
            imagePullSecrets:
              - name: docker-login
        shutdownManager:
          image: envoyproxy/gateway:v1.7.2
      type: Kubernetes
    proxyTopologyInjector:
      disabled: true
