// Code generated by pkg/config/schema/codegen/tools/collections.main.go. DO NOT EDIT.

package kubetypes

import (
	"github.com/lx1036/gateway/pkg/config"
	"github.com/lx1036/gateway/pkg/config/schema/gvk"
	k8sioapiappsv1 "k8s.io/api/apps/v1"
	k8sioapicorev1 "k8s.io/api/core/v1"
	k8sioapidiscoveryv1 "k8s.io/api/discovery/v1"
	sigsk8siogatewayapiinferenceextensionapiv1 "sigs.k8s.io/gateway-api-inference-extension/api/v1"
	sigsk8siogatewayapiapisv1 "sigs.k8s.io/gateway-api/apis/v1"
	sigsk8siogatewayapiapisv1alpha2 "sigs.k8s.io/gateway-api/apis/v1alpha2"
	sigsk8siogatewayapiapisv1beta1 "sigs.k8s.io/gateway-api/apis/v1beta1"
	sigsk8siogatewayapiapisxv1alpha1 "sigs.k8s.io/gateway-api/apisx/v1alpha1"

	istioioapiextensionsv1alpha1 "istio.io/api/extensions/v1alpha1"
	istioioapinetworkingv1alpha3 "istio.io/api/networking/v1alpha3"
	apiistioioapiextensionsv1alpha1 "istio.io/client-go/pkg/apis/extensions/v1alpha1"
	apiistioioapinetworkingv1alpha3 "istio.io/client-go/pkg/apis/networking/v1alpha3"
)

func getGvk(obj any) (config.GroupVersionKind, bool) {
	switch obj.(type) {
	case *sigsk8siogatewayapiapisv1.BackendTLSPolicy:
		return gvk.BackendTLSPolicy, true
	case *k8sioapicorev1.ConfigMap:
		return gvk.ConfigMap, true
	case *k8sioapiappsv1.DaemonSet:
		return gvk.DaemonSet, true
	case *k8sioapiappsv1.Deployment:
		return gvk.Deployment, true
	case *k8sioapidiscoveryv1.EndpointSlice:
		return gvk.EndpointSlice, true
	case *k8sioapicorev1.Endpoints:
		return gvk.Endpoints, true
	case *istioioapinetworkingv1alpha3.EnvoyFilter:
		return gvk.EnvoyFilter, true
	case *apiistioioapinetworkingv1alpha3.EnvoyFilter:
		return gvk.EnvoyFilter, true
	case *sigsk8siogatewayapiapisv1.GRPCRoute:
		return gvk.GRPCRoute, true
	case *sigsk8siogatewayapiapisv1.GatewayClass:
		return gvk.GatewayClass, true
	case *sigsk8siogatewayapiapisv1.HTTPRoute:
		return gvk.HTTPRoute, true
	case *sigsk8siogatewayapiinferenceextensionapiv1.InferencePool:
		return gvk.InferencePool, true
	case *sigsk8siogatewayapiapisv1.Gateway:
		return gvk.KubernetesGateway, true
	case *k8sioapicorev1.Namespace:
		return gvk.Namespace, true
	case *k8sioapicorev1.Node:
		return gvk.Node, true
	case *k8sioapicorev1.Pod:
		return gvk.Pod, true
	case *sigsk8siogatewayapiapisv1beta1.ReferenceGrant:
		return gvk.ReferenceGrant, true
	case *k8sioapicorev1.Secret:
		return gvk.Secret, true
	case *k8sioapicorev1.Service:
		return gvk.Service, true
	case *k8sioapicorev1.ServiceAccount:
		return gvk.ServiceAccount, true
	case *k8sioapiappsv1.StatefulSet:
		return gvk.StatefulSet, true
	case *sigsk8siogatewayapiapisv1alpha2.TCPRoute:
		return gvk.TCPRoute, true
	case *sigsk8siogatewayapiapisv1alpha2.TLSRoute:
		return gvk.TLSRoute, true
	case *sigsk8siogatewayapiapisv1alpha2.UDPRoute:
		return gvk.UDPRoute, true
	case *istioioapiextensionsv1alpha1.WasmPlugin:
		return gvk.WasmPlugin, true
	case *apiistioioapiextensionsv1alpha1.WasmPlugin:
		return gvk.WasmPlugin, true
	case *sigsk8siogatewayapiapisxv1alpha1.XBackendTrafficPolicy:
		return gvk.XBackendTrafficPolicy, true
	default:
		return config.GroupVersionKind{}, false
	}
}
