



apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-gateway-config
  namespace: envoy-gateway-system
data:
  envoy-gateway.yaml: >+
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: EnvoyGateway
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller

    logging:
      level:
        default: info

    provider:
      kubernetes:
        rateLimitDeployment:
          container:
            image: harbor.example.cn/esx-k8s/envoyproxy/ratelimit:0141a24f
          patch:
            type: StrategicMerge
            value:
              spec:
                template:
                  spec:
                    containers:
                      - imagePullPolicy: IfNotPresent
                        name: envoy-ratelimit
          pod:
            imagePullSecrets:
              - name: docker-login
        shutdownManager:
          image: harbor.example.cn/esx-k8s/envoyproxy/gateway:v1.6.1-amd64
      type: Kubernetes

    proxyTopologyInjector:
      disabled: true

    extensionApis:
      # Not strictly required, but recommended for backward/future compatibility.
      enableEnvoyPatchPolicy: true
      # Required: Enable Backend API for AI service backends.
      enableBackend: true
    
    # Required: AI Gateway needs to fine-tune xDS resources generated by Envoy Gateway.
    extensionManager:
      # Enable InferencePool custom resource support
      backendResources:
        - group: inference.networking.k8s.io
          kind: InferencePool
          version: v1

      hooks:
        xdsTranslator:
          translation:
            listener:
              includeAll: true
            route:
              includeAll: true
            cluster:
              includeAll: true
            secret:
              includeAll: true
          post:
            - Translation
            - Cluster
            - Route

      service:
        fqdn:
          # IMPORTANT: Update this to match your AI Gateway controller service
          # Format: <service-name>.<namespace>.svc.cluster.local
          # Default if you followed the installation steps above:
          hostname: ai-gateway-controller.envoy-ai-gateway-system.svc.cluster.local
          port: 1063
