// Code generated by pkg/config/schema/codegen/tools/collections.main.go. DO NOT EDIT.

package gvk

import (
	"github.com/lx1036/gateway/pkg/config"
	"github.com/lx1036/gateway/pkg/config/schema/gvr"
	"github.com/lx1036/gateway/pkg/config/schema/kind"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	BackendTLSPolicy           = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "BackendTLSPolicy"}
	ConfigMap                  = config.GroupVersionKind{Group: "", Version: "v1", Kind: "ConfigMap"}
	DaemonSet                  = config.GroupVersionKind{Group: "apps", Version: "v1", Kind: "DaemonSet"}
	Deployment                 = config.GroupVersionKind{Group: "apps", Version: "v1", Kind: "Deployment"}
	EndpointSlice              = config.GroupVersionKind{Group: "discovery.k8s.io", Version: "v1", Kind: "EndpointSlice"}
	Endpoints                  = config.GroupVersionKind{Group: "", Version: "v1", Kind: "Endpoints"}
	EnvoyFilter                = config.GroupVersionKind{Group: "networking.istio.io", Version: "v1alpha3", Kind: "EnvoyFilter"}
	GRPCRoute                  = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "GRPCRoute"}
	GRPCRoute_v1alpha2         = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "GRPCRoute"}
	GatewayClass               = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "GatewayClass"}
	GatewayClass_v1alpha2      = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "GatewayClass"}
	GatewayClass_v1beta1       = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1beta1", Kind: "GatewayClass"}
	HTTPRoute                  = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "HTTPRoute"}
	HTTPRoute_v1alpha2         = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "HTTPRoute"}
	HTTPRoute_v1beta1          = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1beta1", Kind: "HTTPRoute"}
	InferencePool              = config.GroupVersionKind{Group: "inference.networking.k8s.io", Version: "v1", Kind: "InferencePool"}
	KubernetesGateway          = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1", Kind: "Gateway"}
	KubernetesGateway_v1alpha2 = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "Gateway"}
	KubernetesGateway_v1beta1  = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1beta1", Kind: "Gateway"}
	Namespace                  = config.GroupVersionKind{Group: "", Version: "v1", Kind: "Namespace"}
	Node                       = config.GroupVersionKind{Group: "", Version: "v1", Kind: "Node"}
	Pod                        = config.GroupVersionKind{Group: "", Version: "v1", Kind: "Pod"}
	ReferenceGrant             = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1beta1", Kind: "ReferenceGrant"}
	ReferenceGrant_v1alpha2    = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "ReferenceGrant"}
	Secret                     = config.GroupVersionKind{Group: "", Version: "v1", Kind: "Secret"}
	Service                    = config.GroupVersionKind{Group: "", Version: "v1", Kind: "Service"}
	ServiceAccount             = config.GroupVersionKind{Group: "", Version: "v1", Kind: "ServiceAccount"}
	StatefulSet                = config.GroupVersionKind{Group: "apps", Version: "v1", Kind: "StatefulSet"}
	TCPRoute                   = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "TCPRoute"}
	TLSRoute                   = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "TLSRoute"}
	UDPRoute                   = config.GroupVersionKind{Group: "gateway.networking.k8s.io", Version: "v1alpha2", Kind: "UDPRoute"}
	WasmPlugin                 = config.GroupVersionKind{Group: "extensions.istio.io", Version: "v1alpha1", Kind: "WasmPlugin"}
	XBackendTrafficPolicy      = config.GroupVersionKind{Group: "gateway.networking.x-k8s.io", Version: "v1alpha1", Kind: "XBackendTrafficPolicy"}
)

// ToGVR converts a GVK to a GVR.
func ToGVR(g config.GroupVersionKind) (schema.GroupVersionResource, bool) {
	switch g {
	case BackendTLSPolicy:
		return gvr.BackendTLSPolicy, true
	case ConfigMap:
		return gvr.ConfigMap, true
	case DaemonSet:
		return gvr.DaemonSet, true
	case Deployment:
		return gvr.Deployment, true
	case EndpointSlice:
		return gvr.EndpointSlice, true
	case Endpoints:
		return gvr.Endpoints, true
	case EnvoyFilter:
		return gvr.EnvoyFilter, true
	case GRPCRoute:
		return gvr.GRPCRoute, true
	case GRPCRoute_v1alpha2:
		return gvr.GRPCRoute_v1alpha2, true
	case GatewayClass:
		return gvr.GatewayClass, true
	case GatewayClass_v1alpha2:
		return gvr.GatewayClass_v1alpha2, true
	case GatewayClass_v1beta1:
		return gvr.GatewayClass_v1beta1, true
	case HTTPRoute:
		return gvr.HTTPRoute, true
	case HTTPRoute_v1alpha2:
		return gvr.HTTPRoute_v1alpha2, true
	case HTTPRoute_v1beta1:
		return gvr.HTTPRoute_v1beta1, true
	case InferencePool:
		return gvr.InferencePool, true
	case KubernetesGateway:
		return gvr.KubernetesGateway, true
	case KubernetesGateway_v1alpha2:
		return gvr.KubernetesGateway_v1alpha2, true
	case KubernetesGateway_v1beta1:
		return gvr.KubernetesGateway_v1beta1, true
	case Namespace:
		return gvr.Namespace, true
	case Node:
		return gvr.Node, true
	case Pod:
		return gvr.Pod, true
	case ReferenceGrant:
		return gvr.ReferenceGrant, true
	case ReferenceGrant_v1alpha2:
		return gvr.ReferenceGrant_v1alpha2, true
	case Secret:
		return gvr.Secret, true
	case Service:
		return gvr.Service, true
	case ServiceAccount:
		return gvr.ServiceAccount, true
	case StatefulSet:
		return gvr.StatefulSet, true
	case TCPRoute:
		return gvr.TCPRoute, true
	case TLSRoute:
		return gvr.TLSRoute, true
	case UDPRoute:
		return gvr.UDPRoute, true
	case WasmPlugin:
		return gvr.WasmPlugin, true
	case XBackendTrafficPolicy:
		return gvr.XBackendTrafficPolicy, true
	}

	return schema.GroupVersionResource{}, false
}

func ToKind(g config.GroupVersionKind) (kind.Kind, bool) {
	switch g {
	case BackendTLSPolicy:
		return kind.BackendTLSPolicy, true
	case ConfigMap:
		return kind.ConfigMap, true
	case DaemonSet:
		return kind.DaemonSet, true
	case Deployment:
		return kind.Deployment, true
	case EndpointSlice:
		return kind.EndpointSlice, true
	case Endpoints:
		return kind.Endpoints, true
	case EnvoyFilter:
		return kind.EnvoyFilter, true
	case GRPCRoute:
		return kind.GRPCRoute, true
	case GatewayClass:
		return kind.GatewayClass, true
	case HTTPRoute:
		return kind.HTTPRoute, true
	case InferencePool:
		return kind.InferencePool, true
	case KubernetesGateway:
		return kind.KubernetesGateway, true
	case Namespace:
		return kind.Namespace, true
	case Node:
		return kind.Node, true
	case Pod:
		return kind.Pod, true
	case ReferenceGrant:
		return kind.ReferenceGrant, true
	case Secret:
		return kind.Secret, true
	case Service:
		return kind.Service, true
	case ServiceAccount:
		return kind.ServiceAccount, true
	case StatefulSet:
		return kind.StatefulSet, true
	case TCPRoute:
		return kind.TCPRoute, true
	case TLSRoute:
		return kind.TLSRoute, true
	case UDPRoute:
		return kind.UDPRoute, true
	case WasmPlugin:
		return kind.WasmPlugin, true
	case XBackendTrafficPolicy:
		return kind.XBackendTrafficPolicy, true
	}

	return kind.Unknown, false
}

func MustToKind(g config.GroupVersionKind) kind.Kind {
	r, ok := ToKind(g)
	if !ok {
		panic("unknown kind: " + g.String())
	}
	return r
}

// MustToGVR converts a GVK to a GVR, and panics if it cannot be converted
// Warning: this is only safe for known types; do not call on arbitrary GVKs
func MustToGVR(g config.GroupVersionKind) schema.GroupVersionResource {
	r, ok := ToGVR(g)
	if !ok {
		panic("unknown kind: " + g.String())
	}
	return r
}

// FromGVR converts a GVR to a GVK.
func FromGVR(g schema.GroupVersionResource) (config.GroupVersionKind, bool) {
	switch g {
	case gvr.BackendTLSPolicy:
		return BackendTLSPolicy, true
	case gvr.ConfigMap:
		return ConfigMap, true
	case gvr.DaemonSet:
		return DaemonSet, true
	case gvr.Deployment:
		return Deployment, true
	case gvr.EndpointSlice:
		return EndpointSlice, true
	case gvr.Endpoints:
		return Endpoints, true
	case gvr.EnvoyFilter:
		return EnvoyFilter, true
	case gvr.GRPCRoute:
		return GRPCRoute, true
	case gvr.GatewayClass:
		return GatewayClass, true
	case gvr.HTTPRoute:
		return HTTPRoute, true
	case gvr.InferencePool:
		return InferencePool, true
	case gvr.KubernetesGateway:
		return KubernetesGateway, true
	case gvr.Namespace:
		return Namespace, true
	case gvr.Node:
		return Node, true
	case gvr.Pod:
		return Pod, true
	case gvr.ReferenceGrant:
		return ReferenceGrant, true
	case gvr.Secret:
		return Secret, true
	case gvr.Service:
		return Service, true
	case gvr.ServiceAccount:
		return ServiceAccount, true
	case gvr.StatefulSet:
		return StatefulSet, true
	case gvr.TCPRoute:
		return TCPRoute, true
	case gvr.TLSRoute:
		return TLSRoute, true
	case gvr.UDPRoute:
		return UDPRoute, true
	case gvr.WasmPlugin:
		return WasmPlugin, true
	case gvr.XBackendTrafficPolicy:
		return XBackendTrafficPolicy, true
	}

	return config.GroupVersionKind{}, false
}

// FromGVR converts a GVR to a GVK, and panics if it cannot be converted
// Warning: this is only safe for known types; do not call on arbitrary GVRs
func MustFromGVR(g schema.GroupVersionResource) config.GroupVersionKind {
	r, ok := FromGVR(g)
	if !ok {
		panic("unknown kind: " + g.String())
	}
	return r
}

// KebabKind returns the kebab-case version of a Kind string.
// This is a generated mapping to avoid runtime allocations from string conversion.
func KebabKind(k string) string {
	switch k {
	case "BackendTLSPolicy":
		return "backend-tls-policy"
	case "ConfigMap":
		return "config-map"
	case "DaemonSet":
		return "daemon-set"
	case "Deployment":
		return "deployment"
	case "EndpointSlice":
		return "endpoint-slice"
	case "Endpoints":
		return "endpoints"
	case "EnvoyFilter":
		return "envoy-filter"
	case "GRPCRoute":
		return "grpc-route"
	case "Gateway":
		return "gateway"
	case "GatewayClass":
		return "gateway-class"
	case "HTTPRoute":
		return "http-route"
	case "InferencePool":
		return "inference-pool"
	case "Namespace":
		return "namespace"
	case "Node":
		return "node"
	case "Pod":
		return "pod"
	case "ReferenceGrant":
		return "reference-grant"
	case "Secret":
		return "secret"
	case "Service":
		return "service"
	case "ServiceAccount":
		return "service-account"
	case "StatefulSet":
		return "stateful-set"
	case "TCPRoute":
		return "tcp-route"
	case "TLSRoute":
		return "tls-route"
	case "UDPRoute":
		return "udp-route"
	case "WasmPlugin":
		return "wasm-plugin"
	case "XBackendTrafficPolicy":
		return "x-backend-traffic-policy"
	}
	return ""
}
